apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-fsx-san-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-fsx-san-clone
  template:
    metadata:
      labels:
        app: mysql-fsx-san-clone
    spec:
      containers:
        - image: mysql:8.0.20
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-san
                  key: password
          volumeMounts:
            - name: mysqlvol
              mountPath: /var/lib/mysql
      volumes:
        - name: mysqlvol
          persistentVolumeClaim:
            claimName: mysql-volume-san-clone
