kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volume-san
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fsx-basic-san
