creator_tag           = "<Creator Tag>"
environment           = "<Environment Name>"
aws_location          = "ap-southeast-1"
availability_zones    = ["ap-southeast-1a", "ap-southeast-1b"]
ec2_instance_type     = "t3.2xlarge"
ec2_instance_keypair  = "<Name of the Key Value Pair>"
ec2_iam_role          = "<Name of the role>"
fsxn_password         = "P@ssw0rd@123"
volume_security_style = "NTFS"
vpc_cidr              = "10.0.0.0/16"
public_subnets_cidr   = ["10.0.0.0/20", "10.0.16.0/20"]
private_subnets_cidr  = ["10.0.128.0/20", "10.0.144.0/20"]
