apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-fsx-ontap-nas
  namespace: {{ .Values.namespace }}
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: {{ .Values.fsx.managment_lif }}
  dataLIF: {{ .Values.fsx.data_lif }}
  svm: {{ .Values.svm_name }}
  credentials: 
    name: fsx-secret