apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-fsx-ontap-san
  namespace: {{ .Values.namespace }}
spec:
  version: 1
  storageDriverName: ontap-san
  managementLIF: {{ .Values.fsx.managment_lif }}
  svm: {{ .Values.svm_name }}
  credentials: 
    name: fsx-secret