
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    trident.netapp.io/shareToNamespace: '*'
  name: shared-pv
  namespace: vector
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ .Values.configuration.storageclass_nas }}