#!/bin/bash
################################################################################
# THIS SOFTWARE IS PROVIDED BY NETAPP "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL NETAPP BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR'
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################
#
# This script is used to delete a storage virtual machine from a
# FSxN filesystem.
################################################################################

################################################################################
#  This function just outputs the usage information and exits.
################################################################################
usage () {
cat 1>&2 <<EOF
Usage: $(basename $0) -i svmID [-r region] 
Where:
  svmID: Is the ID of the storage virtual machine you want to delete.
  region: Is the AWS region where the SVM resides.
EOF
  exit 1
}

################################################################################
# Main logic starts here.
################################################################################
tmpout=/tmp/fsx_svm_create.$$
volumesFile=/tmp/fsx_svm_create-volumes.$$
trap 'rm -f $tmpout volumesFile' exit

if which aws jq > /dev/null 2>&1; then
  :
else
  echo "Error, both the 'aws' and 'jq' commands are required to run this script." 1>&2
  exit 1
fi
#
# Set any defaults.
region=$(aws configure list | egrep '^.*egion ' | awk '{print $2}')
#
# Process command line arguments.
while getopts "i:r:" option; do
  case $option in
    i) svmID=$OPTARG
      ;;
    r) region=$OPTARG
      ;;
    *) echo "Error, unknown option '$option'." 1>&2
      usage
      ;;
  esac
  shift
done
#
# Ensure all the required parameters have been provided.
if [ -z "$svmID" ]; then
  echo "Error, missing reuqired arguments." 1>&2
  usage
  exit 1
fi

aws fsx delete-storage-virtual-machine --region=$region --storage-virtual-machine-id $svmID > $tmpout 2>&1

if [ $? != "0" ]; then
  echo "Failed to delete storage virtual machine." 1>&2
  cat $tmpout
  exit 1
else
  status=$(jq -r .Lifecycle $tmpout)
  if [ "$status" == "DELETING" ]; then
    echo "Storage Virtual Machine with an id of '$svmID' is being deleted."
    exit 0
  else
    echo "Unknown status '$status'. Complete output returned from the AWS api:"
    cat $tmpout
    exit 1
  fi
fi
