#!/bin/bash
################################################################################
# THIS SOFTWARE IS PROVIDED BY NETAPP "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL NETAPP BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR'
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################
#
################################################################################
# This script will list all the AWS FSx volumes that a user has access to.
# It will list:
#   o Region
#   o File System ID
#   o File System Name - optional
#   o Volume ID
#   o Volume Name
#
################################################################################

################################################################################
# This function outputs the usage information and exists.
################################################################################
usage () {
  cat 1>&2 <<EOF
Usage $(basename $0) [-r region] [-a] [-n] [-f] [-s svmID]
  Where: -r region allows you to specify the region you want the list from.
         -a means all regions.
         -f means include the file system name.
         -s svmID - Only show volumes that are under the specified SVM ID.
         -n means to exclude svm root volumes. Only works in conjunction with the -s option.
EOF
  exit 1
}

################################################################################
# Main logic starts here.
################################################################################

tmpout=/tmp/list_aws_vol-out.$$
tmpout2=/tmp/list_aws_vol-out0.$$
trap 'rm -f $tmpout $tmpout2' exit
#
# Check that the required utilities are installed.
if which aws jq > /dev/null 2>&1; then
  :
else
  echo "Error, this script requires both the 'aws' and 'jq' commands to run." 1>&2
  exit 1
fi
#
# Process command line arguments.
allRegions=false
region=$(aws configure list | egrep '^.*egion ' | awk '{print $2}')
includeFsName=false
excludeRoot=false
while getopts "fanr:s:" option; do
  case "$option" in
    r) region="$OPTARG"
      ;;
    a) allRegions=true
      ;;
    f) includeFsName=true
      ;;
    n) excludeRoot=true
      ;;
    s) svmID="$OPTARG"
      ;;
    *) echo "Error, unknown option '$option'." 1>&2
      usage
      ;;
  esac
done

if [ "$allRegions" = "true" ]; then
  regions=$(aws ec2 describe-regions --query "Regions[].RegionName" --output=json | jq -r '.[]')
else
  regions=$region
fi
#
# Loop on all the regions.
for region in $regions; do
  #
  # Check that the fsx service is supported in thie region
  if [ ! -z "$(getent hosts fsx.$region.amazonaws.com)" ]; then
    if [ -z "$svmID" ]; then
      aws fsx describe-volumes --region=$region | jq -r '.Volumes[] | .FileSystemId + "," + .Name + "," + .VolumeId' | sort > $tmpout
    else
      if [ "$excludeRoot" != "true" ]; then
        aws fsx describe-volumes --region=$region | jq -r ".Volumes[] | if(.OntapConfiguration.StorageVirtualMachineId == \"$svmID\") then .FileSystemId + \",\" + .Name + \",\" + .VolumeId else empty end" | sort > $tmpout
      else
        aws fsx describe-volumes --region=$region | jq -r ".Volumes[] | if(.OntapConfiguration.StorageVirtualMachineId == \"$svmID\" and (.OntapConfiguration.StorageVirtualMachineRoot | not)) then .FileSystemId + \",\" + .Name + \",\" + .VolumeId else empty end" | sort > $tmpout
      fi
    fi
  
    if [ $includeFsName == "true" ]; then
      aws fsx describe-file-systems --region=$region | jq -r '.FileSystems[] | .FileSystemId + "," + (.Tags[] | select(.Key == "Name") .Value)' > $tmpout2
      awk -F, -v region=$region 'BEGIN {first=1; maxNameLen=0; while(getline < "'$tmpout2'") {fss[$1]=$2; if(length($2) > maxNameLen) {maxNameLen=length($2)}}; maxNameLen +=2; formatStr="%12s %20s%-"maxNameLen"s %23s %s\n"}; {if(first) {printf "\n"; printf formatStr, "Region", "FileSystem ID", "(Name)", "Volume ID", "Volume Name"; first=0}; name="("fss[$1]")"; printf formatStr, region, $1, name, $3, $2}' < $tmpout
    else
      awk -F, -v region=$region 'BEGIN {first=1; formatStr="%12s %23s %23s %s\n"}; {if(first) {printf "\n"; printf formatStr, "Region", "FileSystem ID", "Volume ID", "Volume Name"; first=0}; printf formatStr, region, $1, $3, $2}' < $tmpout
    fi
  else
    if [ $allRegions != "true" ]; then
      printf "The fsx service is currently not supported in the $region region.\n"
    fi
  fi
done
