role: "Agent"

image:
  repository: timberio/vector
  tag: "0.35.0-alpine"

existingConfigMaps: 
  - "vector-configmap-test"
dataDir: "/vector-data-dir"

service:
  ports:
    - name: prom-exporter
      protocol: TCP
      port: 9090
      targetPort: 9090


extraVolumeMounts:
  - name: shared-logs
    mountPath: /logs
    readOnly: false
    subPathExpr: $(VECTOR_SELF_NODE_NAME)

extraVolumes:
  - name: shared-logs
    persistentVolumeClaim:
      claimName: shared-pv