#!/bin/bash
#
# This script adds an organization to a BlueXP account.
#
################################################################################
# Display usage information then exits the script.
################################################################################
usage () {
  cat 1>&2 <<EOF
Usage: $(basename $0) -t REFRESH_TOKEN -o ORGANIZATION_NAME [-e ENDPOINT] [-b BEARER_TOKEN] [-g]

Where: REFRESH_TOKEN - Is a refresh token used to obtain an access token needed
                       to run the Workload Factory APIs. You can obtain a refresh
                       token by going to https://services.cloud.netapp.com/refresh-token
       ORGANIZATION_NAME - Is the name of the organization to create.
       ENDPOINT - Is the BlueXP API endpoint to use. The default is api.bluexp.netapp.com.
       BEARER_TOKEN - Is an access token that can be used instead of a refresh token. If you
                      provide a bearer token, the script will not attempt to obtain a new
                      access token using the refresh token.
      -g - If specified the account will be created in the GovCloud region.

Instead of passing parameters on the command line, you can set the following
environment variables:

    export REFRESH_TOKEN=<REFRESH_TOKEN>
EOF
  exit 1
}

################################################################################
# Main logic starts here.
################################################################################
tmpout=$(mktemp /tmp/add_organization_to_bluexp-out.XXXXXX)
tmperr=$(mktemp /tmp/add_organization_to_bluexp-err.XXXXXX)
trap 'rm -f $tmpout $tmperr' exit
#
# Source the wf_utils file.
wf_utils=$(command -v wf_utils)
if [ -z "$wf_utils" ]; then
  if [ ! -x "./wf_utils" ]; then
    cat >&2 <<EOF
Error: The 'wf_utils' script was not found in the current directory or in the command search path.
It is required to run this script. You can download it from:
https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples
EOF
    exit 1
  else
    wf_utils=./wf_utils
  fi
fi
. "$wf_utils"
#
# Parse the command line options.
: "${ENDPOINT:=api.bluexp.netapp.com}"
GovCloud=false
while getopts "ht:o:e:b:g" opt; do
  case ${opt} in
    t) REFRESH_TOKEN=$OPTARG ;;
    o) ORGANIZATION_NAME=$OPTARG ;;
    e) ENDPOINT="$OPTARG" ;;
    b) BEARER_TOKEN="$OPTARG" ;;
    g) GovCloud=true ;;
    *) usage ;;
  esac
done
#
# Declare an array of required options and the error message to display if they are not set.
declare -A required_options
required_options["ORGANIZATION_NAME"]='Error: You must provide the name of the organization you want to create.\n\n'

check_required_options

if [ -z "$REFRESH_TOKEN" -a -z "$BEATER_TOKEN" ]; then
  echo "Error: You must provide either a refresh token or a bearer token." >&2
  usage
fi
#
# Check that the required commands are available.
for cmd in jq curl; do
  if ! command -v $cmd &> /dev/null; then
    echo "Error: The required command '$cmd' was not found. Please install it." >&2
    exit 1
  fi
done
#
# Get an access token.
if [ -z "$BEARER_TOKEN" ]; then
  token=$(get_token)
else
  token=$BEARER_TOKEN
fi

if [ -z "$token" ]; then
  echo "Failed to get a token."
  exit 1
fi
#
# Add the organization to the BlueXP workspace.
echo -n "Creating organization ${ORGANIZATION_NAME}..."
#run_curl "POST" "$token" "https://$ENDPOINT/tenancy/account/$ORGANIZATION_NAME" $tmpout $tmperr '{"name": "'$ORGANIZATION_NAME'", "resourceType": "organization", "type": "application/vnd.netapp.bxp.resource", "version": "1.0"}' 'application/json'
run_curl "POST" "$token" "https://$ENDPOINT/tenancy/account/$ORGANIZATION_NAME" $tmpout $tmperr '{"isSaasDisabled": '$GovCloud'}' 'application/json'
echo "Done."
