#!/bin/bash
#
# This script adds an organization to a BlueXP account.
#
################################################################################
# Display usage information then exists the script.
################################################################################
usage () {
  cat 1>&2 <<EOF
Usage: $(basename $0) -t REFRESH_TOKEN -o ORGANIZATION_NAME

Where: REFRESH_TOKEN - Is a refresh token used to obtain an access token needed
                       to run the Workload Factory APIs. You can obtain a refresh
                       token by going to https://services.cloud.netapp.com/refresh-token
       ORGANIZATION_NAME - Is the name of the organization to create.

Instead of passing parameters on the command line, you can set the following
environment variables:

    export REFRESH_TOKEN=<REFRESH_TOKEN>
EOF
  exit 1
}

################################################################################
# Main logic starts here.
################################################################################
tmpout=$(mktemp /tmp/add_organization_to_bluexp-out.XXXXXX)
tmperr=$(mktemp /tmp/add_organization_to_bluexp-err.XXXXXX)
trap 'rm -f $tmpout $tmperr' exit
#
# Source the wf_utils file.
wf_utils=$(command -v wf_utils)
if [ -z "$wf_utils" ]; then
  if [ ! -x "./wf_utils" ]; then
    cat >&2 <<EOF
Error: The 'wf_utils' script was not found in the current directory or in the command search path.
It is required to run this script. You can download it from:
https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples
EOF
    exit 1
  else
    wf_utils=./wf_utils
  fi
fi
. "$wf_utils"
#
# Parse the command line options.
while getopts "ht:o:" opt; do
  case ${opt} in
    t) REFRESH_TOKEN=$OPTARG ;;
    o) ORGANIZATION_NAME=$OPTARG ;;
    *) usage ;;
  esac
done
#
# Declare an array of required options and the error message to display if they are not set.
declare -A required_options
required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh token is required to run this script. It can be obtained from this web page:
  https://services.cloud.netapp.com/refresh-token\n\n'
required_options["ORGANIZATION_NAME"]='Error: You must provide the name of the organization you want to create.\n\n'

check_required_options
#
# Check that the required commands are available.
for cmd in jq curl; do
  if ! command -v $cmd &> /dev/null; then
    echo "Error: The required command '$cmd' was not found. Please install it." >&2
    exit 1
  fi
done
#
# Get an access token.
token=$(get_token)
if [ -z "$token" ]; then
  echo "Failed to get a token."
  exit 1
fi
#
# Add the organization to the BlueXP workspace.
echo -n "Creating organization ${ORGANIZATION_NAME}..."
run_curl "POST" "$token" "https://api.bluexp.netapp.com/tenancy/account/$ORGANIZATION_NAME" $tmpout $tmperr '{"name": "'$ORGANIZATION_NAME'", "resourceType": "organization", "type": "application/vnd.netapp.bxp.resource", "version": "1.0"}' 'application/json'
echo "Done."
