#!/bin/bash
#
################################################################################
# This script is used to get the base EDA -> Latency configuration.
#
# It is dependent on the 'wf_utils' file that is included in this repo. That
# file contains the 'get_token' function that is used to obtain a valid
# access token that is needed to run the Workload Factory APIs. The file needs
# to either be in the command search path or in the current directory.
################################################################################

################################################################################
# This function just prints the usage of this script and exits the program.
################################################################################
usage() {
  cat >&2 <<EOF
This script is used to get the base EDA -> Latency configuration. It will not
report on the latency configuration for individual volumes. To see them use
the -j option.

Usage: $(basename $0) -t refresh_token -a blueXP_account_ID [-j] [-n]

Where: refresh_token - Is a refresh token used to obtain an access token needed
                       to run the Workload Factory APIs. You can obtain a refresh
                       token by going to https://services.cloud.netapp.com/refresh-token
       blueXP_account_ID - is the BlueXP account ID. Run 'list_bluexp_accts' to get a
                           list of accounts you have access to.
       -j - If specified, the output will be in JSON format instead of a table.
       -n - If specified, the volume name will be included. Note, this will take extra time to run.

Instead of passing parameters on the command line, you can set the
following environment variables:

    export REFRESH_TOKEN=<refresh_token>
    export BLUEXP_ACCOUNT_ID=<blueXP_account_ID>
EOF
  exit 1
}

################################################################################
# Main logic starts here.
################################################################################
tmpout=$(mktemp /tmp/list_volumes-out.XXXXXX)
tmpout2=$(mktemp /tmp/list_volumes-out2.XXXXXX)
tmpout3=$(mktemp /tmp/list_volumes-out3.XXXXXX)
tmperr=$(mktemp /tmp/list_volumes-err.XXXXXX)
trap 'rm -f $tmpout $tmpout2 $tmpout3 $tmperr' exit
#
# Source the wf_utils file.
wf_utils=$(command -v wf_utils)
if [ -z "$wf_utils" ]; then
  if [ ! -x "./wf_utils" ]; then
    cat >&2 <<EOF
Error: The 'wf_utils' script was not found in the current directory or in the command search path.
It is required to run this script. You can download it from:
https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples
EOF
    exit 1
  else
    wf_utils=./wf_utils
  fi
fi
. "$wf_utils"
#
# Process command line arguments.
JSON_OUTPUT=false
INCLUDE_NAMES=false
while getopts "ht:a:jn" opt; do
  case $opt in
    t) REFRESH_TOKEN="$OPTARG" ;;
    a) BLUEXP_ACCOUNT_ID="$OPTARG" ;;
    j) JSON_OUTPUT=true ;;
    n) INCLUDE_NAMES=true ;;
    *) usage ;;
  esac
done
#
# Declare an array of required options and the error message to display if they are not set.
declare -A required_options
required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh tokon is required to run this script. It can be obtain from this web page:
  https://services.cloud.netapp.com/refresh-token\n\n'
required_options["BLUEXP_ACCOUNT_ID"]='Error: A BlueXP account ID is required to run this script.
You can get the list of accounts you have access to by running the "list_bluexp_accts" script
found in this GitHub repository: https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples\n\n'

check_required_options
#
# Check that the required commands are available.
for cmd in jq curl; do
  if ! command -v $cmd &> /dev/null; then
    echo "Error: The required command '$cmd' not found. Please install it." >&2
    exit 1
  fi
done

token=$(get_token)
if [ -z "$token" ]; then
  echo "Error: Failed to obtain an access token. Exiting." >&2
  exit 1
fi
#
# According to the documentation and some testing, this API doesn't support
# pagination, probably because it didn't used to return volume specific
# configurations.
URL="https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/builders/v1/alarm/configure"
run_curl GET "$token" "$URL" $tmpout $tmperr
if [ "$JSON_OUTPUT" == true ]; then
  if jq -r . $tmpout; then
    :
  else
    cat $tmpout $tmperr
  fi
  exit
fi
#
# First get the default latency configuration.
jq_query='"\(.accountId),\(.createdBy),\(.status),\(.config.warning.readLatency.latencyThresholdMs),\(.config.warning.writeLatency.latencyThresholdMs),\(.config.critical.readLatency.latencyThresholdMs),\(.config.critical.writeLatency.latencyThresholdMs)"'
if jq -r "$jq_query" $tmpout > $tmpout2 2> $tmperr; then
  :
else
  echo "Error: Failed to parse the output from the API." >&2
  cat $tmperr >&2
  exit 1
fi
echo "Default Latency Configuration:"
sort -f $tmpout2 | column -s, -t -R 4,5,6,7 -N "Account ID,Created By,Status,Warning Read Threshold,Warning Write Threshold,Critical Read Threshold,Critical Write Threshold"
#
# Now get the latency configuration for each volume.
if [ $(jq -r '.config.filesystems | length' $tmpout) == "0" ]; then
  exit
fi
jq_query='.config.filesystems | to_entries | .[] | .key + " " + (.value | to_entries | .[] | .key + " " + (.value.warning.readLatency.latencyThresholdMs | tostring) + " " + (.value.warning.writeLatency.latencyThresholdMs | tostring) + " " + (.value.critical.readLatency.latencyThresholdMs | tostring) + " " + (.value.critical.writeLatency.latencyThresholdMs | tostring) + " ")'
if jq -r "$jq_query" $tmpout > $tmpout2 2> $tmperr; then
  :
else
  echo "Error: Failed to parse the output from the API." >&2
  cat $tmperr >&2
  exit 1
fi
if [ "$INCLUDE_NAMES" == false ]; then
  printf "\nVolume specific Latency Configuration:\n"
  sort -f $tmpout2 | column -s' ' -t -R 3,4,5,6 -N "File System ID,Volume ID,Warning Read Threshold,Warning Write Threshold,Critical Read Threshold,Critical Write Threshold"
else
  #
  # Get all the unique file systems:
  awk '{print $1}' $tmpout2 | sort -u > $tmpout
  #
  # Create a lookup table of file system to volume mapping.
  > $tmpout3
  for fs in $(cat $tmpout); do
    list_volumes -f $fs >> $tmpout3
  done

  > $tmpout
  while read fsId volId wrt wwr crt cwt; do
    volumeName=$(grep $volId $tmpout3 | awk '{print $1}')
    if [ -z "$volumeName" ]; then
      volumeName="N/A"
    fi
    echo "$fsId,$volId,$volumeName,$wrt,$wwr,$crt,$cwt," >> $tmpout
  done < $tmpout2
  printf "\nVolume specific Latency Configuration:\n"
  sort -f $tmpout | column -s, -t -R 4,5,6,7 -N "File System ID,Volume ID,Volume Name,Warning Read Threshold,Warning Write Threshold,Critical Read Threshold,Critical Write Threshold"
fi
