#!/bin/bash
#
# This script is used to list all the BlueXP accounts that a user has
# access to. 
#
# It is dependent on the 'wf_utils' file that is included in this repo. That
# file contains the 'get_token' function that is used to obtain a valid
# access token that is needed to run the Workload Factory APIs. The file needs
# to either be in the command search path or in the current directory.
################################################################################

################################################################################
# Display usage information then exits the script.
################################################################################
usage () {
  cat >&2 <<EOF
This script is used to list all the BlueXP accounts (a.k.a. organizations)
that you have access to.

Usage is: $(basename $0) -t refresh_token  [-j] [-e ENDPOINT] [-b BEARER_TOKEN]

Where: refresh_token - Is a refresh token used to obtain an access token needed
                       to run the Workload Factory APIs. You can obtain a refresh
                       token by going to https://services.cloud.netapp.com/refresh-token
      j - Output the raw JSON response from the API instead of a formatted table.
      ENDPOINT - The BlueXP API endpoint to use. Default is api.bluexp.netapp.com.
      BEARER_TOKEN - A valid Bearer token that can be used instead of a refresh token.

Note, instead of passing parameters on the command line, you can set the
following environment variables instead:

    export REFRESH_TOKEN=<refresh_token>
EOF
  exit 1
}

tmpout=/tmp/list_accounts-out.$$
tmperr=/tmp/list_accounts-err.$$
trap 'rm -f $tmpout $tmperr' exit
#
# Source the wf_utils file.
wf_utils=$(command -v wf_utils)
if [ -z "$wf_utils" ]; then
  if [ ! -x "./wf_utils" ]; then
    cat <<EOF >&2
Error: The 'wf_utils' script was not found in the current directory or in the command search path.
It is required to run this script. You can download it from:
https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples
EOF
    exit 1
  else
    wf_utils=./wf_utils
  fi
fi
. "$wf_utils"
#
# Parse the command line options.
raw=false
: "${ENDPOINT:=api.bluexp.netapp.com}"
while getopts ht:je:b: opt; do
  case $opt in
    t) REFRESH_TOKEN="$OPTARG" ;;
    b) BEARER_TOKEN="$OPTARG" ;;
    j) raw=true ;;
    e) ENDPOINT="$OPTARG" ;;
    *) usage ;;
  esac
done
#
# Declare an array of required options and the error message to display if they are not set.
declare -A required_options
required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh tokon is required to run this script. It can be obtain from this web page:
  https://services.cloud.netapp.com/refresh-token\n\n'

check_required_options
#
# Check that the required commands are available.
for cmd in jq curl; do
  if ! command -v $cmd &> /dev/null; then
    echo "Error: The required command '$cmd' was not found. Please install it." >&2
    exit 1
  fi
done

if [ -z "$BEARER_TOKEN" ]; then
  token=$(get_token)
else
  token="$BEARER_TOKEN"
fi

if [ -z "$token" ]; then
  echo "Error: Failed to obtain an access token. Exiting." >&2
  exit 1
fi
#
# /tenancy/account doesn't provide both the ID and UUID.
#run_curl GET "$token" https://$ENDPOINT/tenancy/account $tmpout $tmperr
run_curl GET "$token" https://$ENDPOINT/v1/management/organizations $tmpout $tmperr
if [ "$raw" = true ]; then
  cat $tmpout
  exit 0
fi

if jq -r '.items[] | "\(.name) \(.legacyId) \(.id) " + ((.tags[] | select (".internal:bxp:gov") | if(."internal:bxp:gov") then ."internal:bxp:gov" else empty end) | tostring) + " " + ((.tags[] | select (".internal:bxp:saas") | if(."internal:bxp:saas") then ."internal:bxp:saas" else empty end) | tostring)' $tmpout > $tmperr; then
  cat $tmperr | column -t -N "Name,ID,Organization ID,GovCloud,SaaS Enabled"
else
  echo "Error: Failed to parse the response from the API." >&2
  exit 1
fi
