#!/bin/bash
#
# This script is used to list all the BlueXP members that are
# associated with the BlueXP account.
#
# It is dependent on the 'wf_utils' file that is included in this repo. That
# file contains the 'get_token' function that is used to obtain a valid
# access token that is needed to run the Workload Factory APIs. The file needs
# to either be in the command search path or in the current directory.
################################################################################

################################################################################
# Display usage information then exits the script.
################################################################################
usage () {
  cat >&2 <<EOF
This script is used to list all the BlueXP members that are
associated with the BlueXP account.

Usage is: $(basename $0) -t refresh_token -u bluexp_account_uuid

Where: refresh_token    - Is a refresh token used to obtain an access token needed
                          to run the Workload Factory APIs. You can obtain a refresh
                          token by going to https://services.cloud.netapp.com/refresh-token
       bluexp_account_uuid - The BlueXP account UUID to list the members for. You can
                             find all the accounts you have access to by running the
                             "list_bluexp_accts" script.

Note, instead of passing parameters on the command line, you can set the
following environment variables instead:

    export REFRESH_TOKEN=<refresh_token>
    export BLUEXP_ACCOUNT_UUID=<bluexp_account_uuid>
EOF
  exit 1
}

tmpout=/tmp/list_bluexp_members-out.$$
tmpout2=/tmp/list_bluexp_members-out2.$$
tmperr=/tmp/list_bluexp_members-err.$$
trap 'rm -f $tmpout $tmpout2 $tmperr' exit
#
# Source the wf_utils file.
wf_utils=$(command -v wf_utils)
if [ -z "$wf_utils" ]; then
  if [ ! -x "./wf_utils" ]; then
    cat <<EOF >&2
Error: The 'wf_utils' script was not found in the current directory or in the command search path.
It is required to run this script. You can download it from:
https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples
EOF
    exit 1
  else
    wf_utils=./wf_utils
  fi
fi
. "$wf_utils"
#
# Parse the command line options.
while getopts ht:u: opt; do
  case $opt in
    t) REFRESH_TOKEN="$OPTARG" ;;
    u) BLUEXP_ACCOUNT_UUID="$OPTARG" ;;
    *) usage ;;
  esac
done
#
# Declare an array of required options and the error message to display if they are not set.
declare -A required_options
required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh tokon is required to run this script. It can be obtain from this web page:
  https://services.cloud.netapp.com/refresh-token\n\n'
required_options["BLUEXP_ACCOUNT_UUID"]='Error: A BlueXP account UUID is required to run this script.
You can see the list of accounts you have access to by running the "list_bluexp_accts" script
found in this GitHub repository: https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples\n\n'

check_required_options
#
# Check that the required commands are available.
for cmd in jq curl; do
  if ! command -v $cmd &> /dev/null; then
    echo "Error: The required command '$cmd' was not found. Please install it." >&2
    exit 1
  fi
done

token=$(get_token)
if [ -z "$token" ]; then
  echo "Error: Failed to obtain an access token. Exiting." >&2
  exit 1
fi
filter=$(urlencode "userType ne 'agent'")
numPerPage=1000
run_curl GET "$token" "https://api.bluexp.netapp.com/v1/management/organizations/$BLUEXP_ACCOUNT_UUID/users?limit=${numPerPage}&filter=$filter" $tmpout $tmperr "" "application/vnd.netapp.bxp.users.extended+json"
count=$(jq -r '.count' $tmpout 2> /dev/null)
if [[ "$count" == 0 ]]; then
  echo "No members found for the specified BlueXP account UUID: $BLUEXP_ACCOUNT_UUID." >&2
  echo "Did you provide the UUID or the iD? This script needs the UUID." >&2
  exit 0
fi 
total=$numPerPage

jq_query='.items[] | .name + "," + if(.userType == "user") then .userType + "," + .id else .userType + "," + .auth0Id end + "," + .email'
if jq -r "$jq_query" $tmpout > $tmpout2 2> $tmperr; then
  :
else
  echo "Error: Failed to parse the response from the API." >&2
  cat $tmperr >&2
  exit 1
fi
#
# Check to see if there are more.
while [ "$total" -lt "$count" ]; do
  run_curl GET "$token" "https://api.bluexp.netapp.com/v1/management/organizations/$BLUEXP_ACCOUNT_UUID/users?limit=${numPerPage}&skip=${total}&filter=$filter" $tmpout $tmperr "" "application/vnd.netapp.bxp.users.extended+json"
  if jq -r "$jq_query" $tmpout >> $tmpout2 2> $tmperr; then
    :
  else
    echo "Failed to parse the output from the API."
    cat $tmperr >&2
    exit 1
  fi
  let total+=numPerPage
done
sort -f $tmpout2 | column -s, -t -N Name,Type,ID,Email
