#!/bin/bash
#
################################################################################
# This script is used to list all the Workload Factory Latency Events for
# the account passed it.
#
# It is dependent on the 'wf_utils' file that is included in this repo. That
# file contains the 'get_token' function that is used to obtain a valid
# access token that is needed to run the Workload Factory APIs. The file needs
# to either be in the command search path or in the current directory.
################################################################################

################################################################################
# This function just prints the usage of this script and exits the program.
################################################################################
usage() {
  cat >&2 <<EOF
This script will list all volumes assoicated with the specified FSx for ONTAP
file system.

Usage: $(basename $0) -t refresh_token -a blueXP_account_ID [-j]

Where: refresh_token - Is a refresh token used to obtain an access token needed
                       to run the Workload Factory APIs. You can obtain a refresh
                       token by going to https://services.cloud.netapp.com/refresh-token
       blueXP_account_ID - is the BlueXP account ID. Run 'list_bluexp_accts' to get a
                           list of accounts you have access to.
       -j - If specified, the output will be in JSON format instead of a table.

Instead of passing parameters on the command line, you can set the
following environment variables:

    export REFRESH_TOKEN=<refresh_token>
    export BLUEXP_ACCOUNT_ID=<blueXP_account_ID>
EOF
  exit 1
}

################################################################################
# Main logic starts here.
################################################################################
tmpout=$(mktemp /tmp/list_volumes-out.XXXXXX)
tmpout2=$(mktemp /tmp/list_volumes-out2.XXXXXX)
tmperr=$(mktemp /tmp/list_volumes-err.XXXXXX)
trap 'rm -f $tmpout $tmpout2 $tmperr' exit
#
# Source the wf_utils file.
wf_utils=$(command -v wf_utils)
if [ -z "$wf_utils" ]; then
  if [ ! -x "./wf_utils" ]; then
    cat >&2 <<EOF
Error: The 'wf_utils' script was not found in the current directory or in the command search path.
It is required to run this script. You can download it from:
https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples
EOF
    exit 1
  else
    wf_utils=./wf_utils
  fi
fi
. "$wf_utils"
#
# Process command line arguments.
JSON_OUTPUT=false
while getopts "ht:a:j" opt; do
  case $opt in
    t) REFRESH_TOKEN="$OPTARG" ;;
    a) BLUEXP_ACCOUNT_ID="$OPTARG" ;;
    j) JSON_OUTPUT=true ;;
    *) usage ;;
  esac
done
#
# Declare an array of required options and the error message to display if they are not set.
declare -A required_options
required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh tokon is required to run this script. It can be obtain from this web page:
  https://services.cloud.netapp.com/refresh-token\n\n'
required_options["BLUEXP_ACCOUNT_ID"]='Error: A BlueXP account ID is required to run this script.
You can get the list of accounts you have access to by running the "list_bluexp_accts" script
found in this GitHub repository: https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples\n\n'

check_required_options
#
# Check that the required commands are available.
for cmd in jq curl; do
  if ! command -v $cmd &> /dev/null; then
    echo "Error: The required command '$cmd' not found. Please install it." >&2
    exit 1
  fi
done

token=$(get_token)
if [ -z "$token" ]; then
  echo "Error: Failed to obtain an access token. Exiting." >&2
  exit 1
fi

if [ "$JSON_OUTPUT" == true ]; then
  jq_query='.'
else
  jq_query='.items[] | "\(.createdAt),\(.fileSystemName),\(.volumeName),\(.volumeId),\(.region),\(.alertType),\(.eventType),\(.metrics.latency),\(.metrics.medianLatency),\(.metrics.iops),\(.metrics.medianOverPct)"'
fi

run_curl GET "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/builders/v1/alarm/volumes" $tmpout $tmperr
if jq -r "$jq_query" $tmpout  > $tmpout2 2> $tmperr; then
  :
else
  echo "Error: Failed to parse the output from the API." >&2
  cat $tmperr >&2
  exit 1
fi
#
# Check to see if there are more.
nextToken=$(jq -r '.nextToken' $tmpout)
while [ "$nextToken" != "null" ]; do
  run_curl GET "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/builders/v1/alarm/volumes?nextToken=$nextToken" $tmpout $tmperr
  if jq -r "$jq_query" $tmpout >> $tmpout2 2> $tmperr; then
    :
  else
    echo "Error: Failed to parse the output from the API." >&2
    cat $tmperr >&2
    exit 1
  fi
  nextToken=$(jq -r '.nextToken' $tmpout)
done

if [ "$JSON_OUTPUT" == true ]; then
  cat $tmpout2
else
  sort -f $tmpout2 | column -s, -t -N "Timestamnp,File System Name,Volume Name,Volume ID,Region,Alert Type,Event Type,Latency,Median Latency,IOPS,Median Over Percent"
fi
