#!/bin/bash
#
################################################################################
# This script is used to create a cifs share in a volume in a FSx for
# ONTAP file system. It will assume that the path is /volume_junction_path
# unless you specify a specific path with the -p option. Note that the path
# must exist. The permissions it will assign to the share will be full
# control to everyone.
#
# Note that if a share with the same name already exists, the script will
# display an error and exit.
#
# It is dependent on the 'wf_utils' file that is included in this repo. That
# file contains the 'get_token' function that is used to obtain a valid
# access token that is needed to run the Workload Factory APIs. The file needs
# to either be in the command search path or in the current directory.
################################################################################

################################################################################
# This function just prints the usage of this script and exits the program.
################################################################################
usage() {
  cat >&2 <<EOF
This script is used to create a cifs share in a volume in a FSx for
ONTAP file system. It will assume that the path is /volume_junction_path
unless you specify a specific path with the -p option. Note that the path
must exist. It will give it full control for everyone permissions to the
share.

If a share with the same name already exists the script will display an error and exit.

Usage: $(basename $0) -t refresh_token -a blueXP_account_ID -c credentials_ID -r aws_region -f filesystem_ID -v volume_ID -n cifs_share_name [-p share_path]

Where: refresh_token - Is a refresh token used to obtain an access token needed
                       to run the Workload Factory APIs. You can obtain a refresh
                       token by going to https://services.cloud.netapp.com/refresh-token
       blueXP_account_ID - is the BlueXP account ID. Run 'list_bluexp_accts' to get a
                           list of accounts you have access to
       credentials_ID    - is the Workload Factory credentials ID for the AWS account. Run
                           'list_credentials' to get a list of credentials you have access to
       aws_region        - is the AWS region where the FSx file systems are located
       filesystem_id     - is the AWS file system ID of the FSx file system where the volume resides
       volume_ID         - is the AWS volume ID of the volume where you want to create the cifs share.
       cifs_share_name   - is the name of the share to create. Only alphanumeric characters, underscores and dashes are allowed.
       share_path        - is the path of the share within the volume. The volume's junction path will be to the share path. If not specified, it will default to /volume_junction_path. Note the path must exist in the volume.

Instead of passing parameters on the command line, you can set the
following environment variables:

    export REFRESH_TOKEN=<refresh_token>
    export BLUEXP_ACCOUNT_ID=<blueXP_account_ID>
    export CREDENTIALS_ID=<credentials_ID>
    export AWS_REGION=<aws_region>
EOF
  exit 1
}

################################################################################
# Main logic starts here.
################################################################################
tmpout=$(mktemp /tmp/create_share-out.XXXXXX)
tmperr=$(mktemp /tmp/create_share-err.XXXXXX)
trap 'rm -f $tmpout $tmperr' exit
#
# Source the wf_utils file.
wf_utils=$(command -v wf_utils)
if [ -z "$wf_utils" ]; then
  if [ ! -x "./wf_utils" ]; then
    cat >&2 <<EOF
Error: The 'wf_utils' script was not found in the current directory or in the command search path.
It is required to run this script. You can download it from:
https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples
EOF
    exit 1
  else
    wf_utils=./wf_utils
  fi
fi
. "$wf_utils"
#
# Process command line options.
while getopts "ht:a:c:r:f:v:n:p:" opt; do
  case $opt in
    t) REFRESH_TOKEN="$OPTARG" ;;
    a) BLUEXP_ACCOUNT_ID="$OPTARG" ;;
    c) CREDENTIALS_ID="$OPTARG" ;;
    r) AWS_REGION="$OPTARG" ;;
    f) FILESYSTEM_ID="$OPTARG" ;;
    v) VOLUME_ID="$OPTARG" ;;
    n) CIFS_SHARE_NAME="$OPTARG" ;;
    p) SHARE_PATH="$OPTARG" ;;
    *) usage ;;
  esac
done
#
# Declare an array of required options and the error message to display if they are not set.
declare -A required_options
required_options["REFRESH_TOKEN"]='Error: A BlueXP refresh token is required to run this script. It can be obtain from this web page:
  https://services.cloud.netapp.com/refresh-token\n\n'
required_options["BLUEXP_ACCOUNT_ID"]='Error: A BlueXP account ID is required to run this script.
You can get the list of accounts you have access to by running the "list_bluexp_accts" script
found in this GitHub repository: https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples\n\n'
required_options["CREDENTIALS_ID"]='Error: A Worload Factory Credential ID is required to run this script.
You can get a list of credentials by running the "list_credentials" script
found in this GitHub repository: https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples\n\n'
required_options["AWS_REGION"]='Error: The AWS region where the file system is located is required.\n\n'
required_options["FILESYSTEM_ID"]='Error: The ID of the FSxN file system is required.\n\n'
required_options["VOLUME_ID"]='Error: An AWS Volume ID is required to run this script.
You can get the list of file systems you have access to by running the "list_volumes" script
found in this GitHub repository: https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/Workload-Factory-API-Samples\n\n'
required_options["CIFS_SHARE_NAME"]='Error: The name of the cifs share is required.\n\n'

check_required_options
#
# Check that the CIFS_SHARE_NAME only contains allowed characters (alphanumeric, underscores and dashes).
if [[ ! "$CIFS_SHARE_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "Error: The CIFS share name can only contain alphanumeric characters, underscores and dashes." >&2
  exit 1
fi
#
# Check if the required commands are available.
for cmd in jq curl; do
  if ! command -v $cmd &> /dev/null; then
    echo "Error: The required command '$cmd' was not found. Please install it." >&2
    exit 1
  fi
done

token=$(get_token)
if [ -z "$token" ]; then
  echo "Error: Failed to obtain an access token. Exiting." >&2
  exit 1
fi
#
# Get the existing shares and the junction path
run_curl GET "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/fsx/v2/credentials/${CREDENTIALS_ID}/regions/${AWS_REGION}/file-systems/${FILESYSTEM_ID}/volumes/${VOLUME_ID}?include=cifsShares" $tmpout $tmperr
cifsShares=$(jq -r '.cifsShares' $tmpout)
alreadExist=$(echo "$cifsShares" | jq -r 'map(select(.name == "'$CIFS_SHARE_NAME'")) | length')
if [ "$alreadExist" -gt 0 ]; then
  echo "A share with the name '$CIFS_SHARE_NAME' already exists. No changes will be made." >&2
  exit 1
fi
junctionPath=$(jq -r '.junctionPath' $tmpout)
if [ -z "$junctionPath" -o "$junctionPath" == "null" ]; then
  echo "Error: The volume doesn't have a junction path." >&2
  exit 1
fi

if [ -z "$SHARE_PATH" ]; then
  SHARE_PATH="$junctionPath"
else
  # Remove leading slash if it exists
  SHARE_PATH="${SHARE_PATH#/}"
  SHARE_PATH="$junctionPath/$SHARE_PATH"
fi
#
# Create a new share definition.
newShare='{"name":"'$CIFS_SHARE_NAME'","path":"'$SHARE_PATH'","acls":[{"userOrGroup":"Everyone","permission":"full_control","type":"windows"}]}'
echo "Creating share named '$CIFS_SHARE_NAME' with path '$SHARE_PATH'."
#
# Add the new share to the existing ones.
cifsShares=$(echo "$cifsShares" | jq -r '. += ['$newShare']')
cifsShares="{\"cifsShares\": $cifsShares}"
run_curl PATCH "$token" "https://api.workloads.netapp.com/accounts/${BLUEXP_ACCOUNT_ID}/fsx/v2/credentials/${CREDENTIALS_ID}/regions/${AWS_REGION}/file-systems/${FILESYSTEM_ID}/volumes/${VOLUME_ID}" $tmpout $tmperr "$cifsShares"
