apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-logs-cm
  namespace: vector

data:
  stdout.toml: |
    data_dir = "/vector-data-dir" 
    api.enabled = true            
    api.address = "0.0.0.0:8686"       
    
    [sources.access_logs]
      type = "file"
      ignore_older_secs = 600
      include = [ "/logs/*/*.log" ]
      read_from = "beginning"   

    #Send structured data to console                                                                                                                                                                                                                                               
    [sinks.sink_console]                                                                                                                                                                                                                                                       
      type = "console"                                                                                                                                                                                                                                                         
      inputs = ["access_logs"]                                                                                                                                                                                                                                                
      target = "stdout"                                                                                                                                                                                                                                                        
      encoding.codec = "text" 

