#
# This Ansible playbook generates an inventory report for all the FSXNs
# in all the AWS regions for the account that it is running under.
#################################################################################
---
- vars:
    report_name: output.txt
#################################################################################
#
# Don't change anything below this line.
#
#################################################################################
    fsxn_regions: []
    opted_in_regions: []

  name: Playbook to generate an inventory report on all the FSxNs.
  hosts: localhost
  collections:
    - amazon.aws
  gather_facts: false

  tasks:
    - name: Make sure the report file is empty.
      ansible.builtin.shell:
        cmd: echo "" > {{ report_name }}

    - name: Get all the regions that support FSxN that are opted into.
      include_tasks: get_fsxn_regions.yaml

    - name: Generate the report for all the FSxNs.
      include_tasks: process_region.yaml
      loop: "{{ fsxn_regions }}"
      loop_control:
        loop_var: region
