apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-san
type: Opaque
stringData:
  password: Netapp1!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-fsx-san
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-fsx-san
  template:
    metadata:
      labels:
        app: mysql-fsx-san
    spec:
      containers:
        - image: mysql:8.0.20
          name: mysql
          ports:
            - containerPort: 3306
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-san
                  key: password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqlvol
      volumes:
        - name: mysqlvol
          persistentVolumeClaim:
            claimName: mysql-volume-san
