apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-nas-clone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fsx-basic-nas
  resources:
    requests:
      storage: 50Gi
  dataSource:
    name: mysql-volume-nas-snap-01
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
