#!/bin/bash
#
################################################################################
# This script create a clnne of a volume in a NetApp ONTAP file system.
################################################################################

################################################################################
################################################################################
usage () {
cat <<EOF
Usage: $(basename $0) [-r region] -l linkArn -s secretArn [-k secretKey] -f fsxId -v svmName -p parentVolumeName [-c cloneVolumeName] -t templete_filename
Notes:
    The default region is whatever the default region is for the AWS CLI.
    The secretKey defaults to 'password'.
    The cloneVolumeName defaults to the parentVolumeName with '_clone' appended.
EOF
}
#
# Set the default values.
linkArn=""
secretArn=""
secretKey="password"
fsxId=""
svmName=""
parentVolumeName=""
cloneVolumeName=""
template=""

region=$(aws configure list | awk '/region/{print $2}')

while getopts "hr:l:s:k:f:v:p:c:t:" opt; do
  case $opt in
    r)
      region=$OPTARG
      ;;
    l)
      linkArn=$OPTARG
      ;;
    s)
      secretArn=$OPTARG
      ;;
    k)
      secretKey=$OPTARG
      ;;
    f)
      fsxId=$OPTARG
      ;;
    v)
      svmName=$OPTARG
      ;;
    p)
      parentVolumeName=$OPTARG
      ;;
    c)
      cloneVolumeName=$OPTARG
      ;;
    t)
      template=$OPTARG
      ;;
    h)
      usage
      exit 1
      ;;
  esac
done

if [ -z "$cloneVolumeName" ]; then
  cloneVolumeName="${parentVolumeName}_clone"
fi

if [ -z "$linkArn" -o -z "$region" -o -z "$secretArn" -o -z "$fsxId" -o -z "$svmName" -o -z "$parentVolumeName" -o -z "$template" ]; then
  echo linkARN="$linkArn" region="$region" secretnArn="$secretArn" fsxid="$fsxId" svm="$svmName" par="$parentVolumeName" tempate="$template"
  echo "Missing required arguments."
  usage
  exit 1
fi

if [ ! -r "$template" ]; then
  echo "Cannot read template file '$template'."
  usage
  exit 1
fi
body=$(cat "$template")
stackName="create-fsxn-clone-$$"
aws cloudformation create-stack --region $region --stack-name $stackName --template-body "$body" --parameters \
  ParameterKey=FileSystemId,ParameterValue=$fsxId \
  ParameterKey=SecretArn,ParameterValue=$secretArn \
  ParameterKey=SecretKey,ParameterValue=$secretKey \
  ParameterKey=LinkArn,ParameterValue=$linkArn \
  ParameterKey=SvmName,ParameterValue=$svmName \
  ParameterKey=ParentVolumeName,ParameterValue=$parentVolumeName \
  ParameterKey=CloneVolumeName,ParameterValue=$cloneVolumeName
