{
 "title": "ONTAP: Cluster",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   },
   {
    "name": "CPU_BUSY",
    "query": "System CPU resource utilization is a computed percentage that indicates how busy the system is based on a combination of the most heavily utilized domain and idle CPU cycles. This metric determines the amount of available CPU and will vary based on domains reaching their limits OR exhausting all idle CPU cycles, whichever comes first."
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Space",
   "type": "stat",
   "description": "Total usable space in bytes, not including WAFL reserve and aggregate Snapshot copy reserve.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Used and Reserved Space",
   "type": "stat",
   "description": "Space used or reserved in bytes. Includes volume guarantees and aggregate metadata.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Available Space",
   "type": "stat",
   "description": "Space available in bytes.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_available{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Space Used %",
   "type": "stat",
   "description": "Percent of space used.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(aggr_space_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})/sum(aggr_space_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by Read Latency",
   "type": "table",
   "description": "Average latency in microseconds for the WAFL filesystem to process read request to the volume; not including request processing or network communication time. node_volume_read_latency is [volume_read_latency](#volume_read_latency) aggregated by `node`.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($TopResources, sum(node_volume_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (node))"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by Write Latency",
   "type": "table",
   "description": "Average latency in microseconds for the WAFL filesystem to process write request to the volume; not including request processing or network communication time. node_volume_write_latency is [volume_write_latency](#volume_write_latency) aggregated by `node`.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk($TopResources, sum(node_volume_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (node))"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by Throughput",
   "type": "table",
   "description": "Node total throughput.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(node_volume_total_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (node)\nand\ntopk(\n  $TopResources,\n  sum by (node) (\n    avg_over_time(node_volume_total_data{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\", node!=\"\"}[3h])\n  )\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by IOPs",
   "type": "table",
   "description": "Number of operations per second serviced by the volume. node_volume_total_ops is [volume_total_ops](#volume_total_ops) aggregated by `node`.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(node_volume_total_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (node)\nand\ntopk(\n  $TopResources,\n  sum by (node) (\n    avg_over_time(node_volume_total_ops{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\", node!=\"\"}[3h])\n  )\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by Average CPU Utilization",
   "type": "table",
   "description": "Average processor utilization across all processors in the system.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($TopResources, sum by (node)(node_avg_processor_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by CPU busy",
   "type": "table",
   "description": "$CPU_BUSY",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($TopResources, sum by (node)(node_cpu_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by Latency",
   "type": "timeseries",
   "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time. node_volume_avg_latency is [volume_avg_latency](#volume_avg_latency) aggregated by `node`.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(node_volume_avg_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (node)\nand\ntopk(\n  $TopResources,\n  sum by (node) (\n    avg_over_time(node_volume_avg_latency{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\", node!=\"\"}[3h])\n  )\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by Throughput",
   "type": "timeseries",
   "description": "Node total throughput.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(node_volume_total_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (node)\nand\ntopk(\n  $TopResources,\n  sum by (node) (\n    avg_over_time(node_volume_total_data{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\", node!=\"\"}[3h])\n  )\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by IOPs",
   "type": "timeseries",
   "description": "Number of operations per second serviced by the volume. node_volume_total_ops is [volume_total_ops](#volume_total_ops) aggregated by `node`.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(node_volume_total_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (node)\nand\ntopk(\n  $TopResources,\n  sum by (node) (\n    avg_over_time(node_volume_total_ops{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\", node!=\"\"}[3h])\n  )\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by Disk Utilization",
   "type": "table",
   "description": "The utilization percent of the disk. node_disk_busy is [disk_busy](#disk_busy) aggregated by `node`.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($TopResources, sum by (node)(node_disk_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}))"
    }
   ]
  },
  {
   "title": "Nodes & Subsystems - $Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "Cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "$Cluster",
     "type": "table",
     "description": "Node details.",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "node_new_status{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
      }
     ]
    },
    {
     "title": "cluster health status",
     "type": "stat",
     "description": "It is an indicator of the overall health status of the cluster, with a value of 1 indicating a healthy status and a value of 0 indicating an unhealthy status.",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cluster_new_status{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
      }
     ]
    },
    {
     "title": "CPU busy",
     "type": "bargauge",
     "description": "$CPU_BUSY",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_cpu_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Average CPU Utilization",
     "type": "bargauge",
     "description": "Average processor utilization across all processors in the system.",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_avg_processor_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "subsystems",
     "type": "table",
     "description": "Cluster subsystem details.",
     "gridPos": { "h": 11, "w": 18, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cluster_subsystem_suppressed_alerts{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "cluster_subsystem_outstanding_alerts{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "cluster_subsystem_new_status{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
      }
     ]
    },
    {
     "title": "Max Disk Utilization by Cluster",
     "type": "bargauge",
     "description": "The utilization percent of the disk. node_disk_max_busy is the maximum of [disk_busy](#disk_busy) for label `node`.",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(node_disk_max_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Avg Disk Utilization by Cluster",
     "type": "bargauge",
     "description": "The utilization percent of the disk. node_disk_busy is [disk_busy](#disk_busy) aggregated by `node`.",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_disk_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Capacity used",
     "type": "bargauge",
     "description": "Aggregate space used percent.",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100*sum(aggr_space_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})/sum(aggr_space_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Node CPU Busy",
     "type": "timeseries",
     "description": "$CPU_BUSY",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_cpu_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node Average CPU Utilization",
     "type": "timeseries",
     "description": "Average processor utilization across all processors in the system.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_avg_processor_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "max(volume_avg_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by(cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Data",
     "type": "timeseries",
     "description": "Volume total throughput.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(volume_total_data{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "IOPs",
     "type": "timeseries",
     "description": "Number of operations per second serviced by the volume.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(volume_total_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Average Disk Utilization by Aggregate",
     "type": "timeseries",
     "description": "The utilization percent of the disk. aggr_disk_busy is [disk_busy](#disk_busy) aggregated by `aggr`.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(aggr_disk_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster, aggr)",
       "legendFormat": "{{cluster}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Average Aggregate Space Used",
     "type": "timeseries",
     "description": "The percentage of disk space currently in use on the referenced file system.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(aggr_space_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster, aggr)",
       "legendFormat": "{{cluster}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Average CPU Utilization",
     "type": "timeseries",
     "description": "Average processor utilization across all processors in the system.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(node_avg_processor_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster, node)",
       "legendFormat": "{{cluster}} - {{node}}"
      }
     ]
    },
    {
     "title": "CPU Busy",
     "type": "timeseries",
     "description": "$CPU_BUSY",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(node_cpu_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}) by (cluster, node)",
       "legendFormat": "{{cluster}} - {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Efficiency Ratios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Reduction",
     "type": "stat",
     "description": "Storage efficiency ratio.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aggr_logical_used_wo_snapshots_flexclones{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})/sum(aggr_physical_used_wo_snapshots_flexclones{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Data Reduction with FlexClones",
     "type": "stat",
     "description": "Storage efficiency ratio with FlexClones.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aggr_logical_used_wo_snapshots{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})/sum(aggr_physical_used_wo_snapshots{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Data Reduction with Snapshots &FlexClones",
     "type": "stat",
     "description": "Storage efficiency ratio of total space used.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aggr_total_logical_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})/sum(aggr_total_physical_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})"
      }
     ]
    },
    {
     "title": "Logical Used",
     "type": "timeseries",
     "description": "Logical used.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (cluster) (aggr_logical_used_wo_snapshots_flexclones{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Physical Used",
     "type": "timeseries",
     "description": "Total data reduction physical used.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (cluster) (aggr_physical_used_wo_snapshots_flexclones{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Logical Used with FlexClones",
     "type": "timeseries",
     "description": "Logical used with flexclones.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (cluster) (aggr_logical_used_wo_snapshots{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Physical Used with FlexClones",
     "type": "timeseries",
     "description": "Total Data Reduction Physical Used with FlexClones.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (cluster) (aggr_physical_used_wo_snapshots{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Logical Used with Snapshots & FlexClones",
     "type": "timeseries",
     "description": "Logical used with snapshots & flexclones.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (cluster) (aggr_total_logical_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Physical Used with Snapshots & FlexClones",
     "type": "timeseries",
     "description": "Physical Used with snapshots & flexclones.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (cluster) (aggr_space_physical_used{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"})",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SVM Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Latency",
     "type": "timeseries",
     "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "svm_vol_avg_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}\nand\ntopk($TopResources, avg_over_time(svm_vol_avg_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[3h] @ end()))",
       "legendFormat": "{{cluster}} - {{svm}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Throughput",
     "type": "timeseries",
     "description": "SVM total throughput.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(\n    svm_vol_read_data{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\"} \n    +\n    svm_vol_write_data{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\"}\n)\nand on(datacenter,cluster, svm)\ntopk(\n  $TopResources,\n  (\n    avg_over_time(svm_vol_read_data{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\"}[3h])\n    + avg_over_time(svm_vol_write_data{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\"}[3h])\n  )\n)",
       "legendFormat": "{{cluster}} - {{svm}}"
      }
     ]
    },
    {
     "title": "Top $TopResources IOPs",
     "type": "timeseries",
     "description": "Number of operations per second serviced by the volume.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "svm_vol_total_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}\nand\ntopk($TopResources, avg_over_time(svm_vol_total_ops{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}[3h] @ end()))",
       "legendFormat": "{{cluster}} - {{svm}}"
      }
     ]
    }
   ]
  }
 ]
}