{
 "title": "ONTAP: Disk",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(disk_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(disk_labels{system_type!=\"7mode\",cluster=~\"$Cluster\"}, node)"
    }
   },
   {
    "name": "Aggregate",
    "query": {
     "query": "label_values(aggr_disk_busy{cluster=~\"$Cluster\",node=~\"$Node\"}, aggr)"
    }
   },
   {
    "name": "Plex",
    "query": {
     "query": "label_values(aggr_disk_busy{cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}, plex)"
    }
   },
   {
    "name": "Raid",
    "query": {
     "query": "label_values(aggr_disk_busy{cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\",plex=~\"$Plex\"}, raid)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Disks by Node(s)",
   "type": "stat",
   "description": "Number of disks.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(disk) (disk_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Failed Disks",
   "type": "stat",
   "description": "Number of failed disks.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(serial_number) (disk_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",failed=\"true\"}) )"
    }
   ]
  },
  {
   "title": "Raid Groups",
   "type": "stat",
   "description": "The utilization percent of the disk. aggr_disk_busy is [disk_busy](#disk_busy) aggregated by `aggr`.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(raid_group) (aggr_disk_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Plexes",
   "type": "stat",
   "description": "The utilization percent of the disk. aggr_disk_busy is [disk_busy](#disk_busy) aggregated by `aggr`.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( count by(plex, aggr) (aggr_disk_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}) )"
    }
   ]
  },
  {
   "title": "Total Disks by Aggregate(s)",
   "type": "stat",
   "description": "Number of disks in the aggregate.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_raid_disk_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"})"
    }
   ]
  },
  {
   "title": "Disk Capacity per Aggregate",
   "type": "table",
   "description": "Disk capacity per aggregate detail.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aggr_raid_disk_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_space_total{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    },
    {
     "expr": "aggr_space_used_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Disk Utilization",
   "type": "table",
   "description": "Highest Disk Utilization per Aggregate for latest record (independent of time range selected).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (aggr,node) (aggr_disk_max_total_transfers{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}) \n  and \ntopk($TopResources, max by (aggr,node) (avg_over_time(aggr_disk_max_total_transfers{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}[3h] @ end())))"
    },
    {
     "expr": "max by (aggr,node) (aggr_disk_max_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}) \n  and \ntopk($TopResources, max by (aggr,node) (avg_over_time(aggr_disk_max_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}[3h] @ end())))"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Max Disk Utilization",
   "type": "timeseries",
   "description": "Highest Disk Utilization per Aggregate in the selected time range.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (aggr_disk_max_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}) \n  and \ntopk($TopResources, max by (node, aggr) (avg_over_time(aggr_disk_max_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}[3h] @ end())))",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Disk Transfers",
   "type": "timeseries",
   "description": "Total number of disk operations involving data transfer initiated per second\n.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (aggr_disk_max_total_transfers{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}) \n  and \ntopk($TopResources, max by (node, aggr) (avg_over_time(aggr_disk_max_total_transfers{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}[3h] @ end())))",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by User Read Chain Length",
   "type": "timeseries",
   "description": "Average number of blocks transferred in each user read operation. aggr_disk_max_user_read_chain is the maximum of [disk_user_read_chain](#disk_user_read_chain) for label `aggr`.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (aggr_disk_max_user_read_chain{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}) \n  and \ntopk($TopResources, max by (node, aggr) (avg_over_time(aggr_disk_max_user_read_chain{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}[3h] @ end())))",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by User Write Chain Length",
   "type": "timeseries",
   "description": "Average number of blocks transferred in each user write operation. aggr_disk_max_user_write_chain is the maximum of [disk_user_write_chain](#disk_user_write_chain) for label `aggr`.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max by (node, aggr) (aggr_disk_max_user_write_chain{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}) \n  and \ntopk($TopResources, max by (node, aggr) (avg_over_time(aggr_disk_max_user_write_chain{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\"}[3h] @ end())))",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Top Disks: Raid-level Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Disks by User Read Latency",
     "type": "timeseries",
     "description": "Average latency per block in microseconds for user read operations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "raid_disk_user_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\",plex=~\"$Plex\",raid=~\"$Raid\"} \n  and \ntopk($TopResources, avg_over_time(raid_disk_user_read_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\",plex=~\"$Plex\",raid=~\"$Raid\"}[3h] @ end()))",
       "legendFormat": "{{cluster}} - {{disk}} - {{plex}} - {{raid}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Disks by User Write Latency",
     "type": "timeseries",
     "description": "Average latency per block in microseconds for user write operations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "raid_disk_user_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\",plex=~\"$Plex\",raid=~\"$Raid\"} \n  and \ntopk($TopResources, avg_over_time(raid_disk_user_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\",plex=~\"$Plex\",raid=~\"$Raid\"}[3h] @ end()))",
       "legendFormat": "{{cluster}} - {{disk}} - {{plex}} - {{raid}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Disks by Total Transfers",
     "type": "timeseries",
     "description": "Total number of disk operations involving data transfer initiated per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "raid_disk_total_transfers{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\",plex=~\"$Plex\",raid=~\"$Raid\"} \n  and \ntopk($TopResources, avg_over_time(raid_disk_total_transfers{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\",plex=~\"$Plex\",raid=~\"$Raid\"}[3h] @ end()))",
       "legendFormat": "{{cluster}} - {{disk}} - {{plex}} - {{raid}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Disks by Disk Busy",
     "type": "timeseries",
     "description": "The utilization percent of the disk in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "raid_disk_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\",plex=~\"$Plex\",raid=~\"$Raid\"} \n  and \ntopk($TopResources, avg_over_time(raid_disk_busy{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",aggr=~\"$Aggregate\",plex=~\"$Plex\",raid=~\"$Raid\"}[3h] @ end()))",
       "legendFormat": "{{cluster}} - {{disk}} - {{plex}} - {{raid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "List of Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks in Cluster",
     "type": "table",
     "description": "Some Clusters don't report average latency, so the values might be 0s.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "disk_bytes_per_sector * disk_sectors{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "disk_stats_io_kbps{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "disk_stats_average_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "disk_uptime{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}"
      },
      {
       "expr": "label_join(disk_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, \"diskStatus\", \" \",\"NonSupportedField\", \"outage\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization: Node-level Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Throughput",
     "type": "timeseries",
     "description": "This panel displays detail of number of disk kilobytes (KB) read/written per second.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "sum (node_disk_data_read{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}) by (node)",
       "legendFormat": "{{node}} - READ"
      },
      {
       "expr": "sum (node_disk_data_written{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}) by (node)",
       "legendFormat": "{{node}} - WRITE"
      }
     ]
    },
    {
     "title": "Disk and Tape Drives Throughput",
     "type": "timeseries",
     "description": "This panel displays detail of bytes written/read through a host adapter.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum (hostadapter_bytes_written{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}) by (node)",
       "legendFormat": "{{node}} - WRITE"
      },
      {
       "expr": "sum (hostadapter_bytes_read{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}) by (node)",
       "legendFormat": "{{node}} - READ"
      }
     ]
    },
    {
     "title": "CP (Consistency Points) Counts",
     "type": "timeseries",
     "description": "This panel displays detail of array of counts of different types of Consistency Points (CP) and average latency in microseconds for the WAFL filesystem to process write request to the volume.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum(wafl_cp_count{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\",metric=~\"back_to_back_CP|deferred_back_to_back_CP\"})",
       "legendFormat": "Back-to-back CP Count"
      },
      {
       "expr": "node_vol_write_latency{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}",
       "legendFormat": "Write Latency {{node}}"
      }
     ]
    },
    {
     "title": "Flash Cache",
     "type": "timeseries",
     "description": "This panel displays detail of external cache hit rate and estimated number of disk reads per second replaced by cache.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (flashcache_hit_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Hit %"
      },
      {
       "expr": "sum (flashcache_disk_reads_replaced{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "HDD Reads Replaced"
      }
     ]
    },
    {
     "title": "Flash Pool",
     "type": "timeseries",
     "description": "This panel displays detail of percentage of HDD read operations replace by SSD and number of HDD read operations replaced by SSD reads per second.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (flashpool_read_ops_replaced_percent{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "Hit %"
      },
      {
       "expr": "sum (flashpool_read_ops_replaced{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"})",
       "legendFormat": "HDD Reads Replaced"
      }
     ]
    }
   ]
  }
 ]
}