{{- range .Values.fsxs.clusters }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: harvest-poller-{{ .name }}
  name: harvest-poller-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: {{ .promPort | quote}}
    port: {{ .promPort }}
    targetPort: {{ .promPort }}
  selector:
    app: harvest-poller-{{ .name }}
---
{{ end }}