apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file harvest-compose.yml --volumes configMap -o kub.yaml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: harvest-service
  name: harvest-service
  namespace: harvest
spec:
  ports:
    - name: "12990"
      port: 12990
      targetPort: 12990
  selector:
    io.kompose.service: harvest-service
status:
  loadBalancer: {}
