#!/bin/bash
################################################################################
# THIS SOFTWARE IS PROVIDED BY NETAPP "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL NETAPP BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR'
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################
#
# This script is used to delete an FSxN volume.
################################################################################

################################################################################
#  This function just outputs the usage information and exits.
################################################################################
usage () {
cat 1>&2 <<EOF
Usage: $(basename $0) -i volumeID [-r region]
where
  volumeID: is the ID of the volume to delete.
  region: is the AWS region where the FSxN filesystem resides.
EOF
  exit 1
}

################################################################################
# Main logic starts here.
################################################################################
tmpout=/tmp/delete-volume.$$
trap 'rm -f $tmpout' exit
#
# Set some defaults.
region=$(aws configure list | egrep '^.*egion ' | awk '{print $2}')
#
# Process command line arguments.
while getopts "i:r:" option; do
  case $option in
    r) region="$OPTARG"
      ;;
    i) volumeId="$OPTARG"
      ;;
    *) usage
      ;;
  esac
done
#
# Ensure all the required parameters have been provided.
if [ -z "$volumeId" ]; then
  echo "Error, missing required arguments." 1>&2
  usage
fi

aws fsx delete-volume --volume-id $volumeId --region=$region --output=json > $tmpout 2>&1

if [ $? != "0" ]; then
  echo "Failed to delete volume." 1>&2
  cat $tmpout 1>&2
  exit 1
else
  status=$(jq -r .Lifecycle $tmpout 2> /dev/null)
  if [ "$status" == "DELETING"  -o "$status" == "PENDING" ]; then
    echo "Volume '$volumeId' is being deleted."
    exit 0
  else
    echo "Unknown status '$status'. Complete output returned from the AWS api:" 1>&2
    cat $tmpout 1>&2
    exit 1
  fi
fi
