

import type { Metadata } from "next";
import './colors.scss';
import styles from './global.module.scss';
import StoreProvider from "@/lib/storeProvider";
import ErrorBoundary from "./ErrorBoundary";
import { DialogContextProvider } from "./components/dsComponents/Dialog";
import NotificationGroup from "./components/NotificationGroup/NotificationGroup";
import RedirectProvider from "./providers/redirectProvider";
import GenAiClerkProvider from "./providers/genAiClerkProvider";
import initTranslations from "../i18n";
import TranslationsProvider from "./components/translationsProvider";

const lang = process.env.NEXT_PUBLIC_LANGUAGE;

export const metadata: Metadata = {
  title: "NetApp GenAI Studio",
  description: "Generated by NetApp",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { resources } = await initTranslations(lang, 'genAi');

  return (
    <html lang="en">
      <GenAiClerkProvider>
        <StoreProvider>
          <body className={`${styles.genAi} ${styles['font-variants']} light-theme`} style={{ margin: 0 }}>
            <DialogContextProvider>
              <ErrorBoundary>
                <RedirectProvider>
                  <TranslationsProvider
                    namespaces={['genAi']}
                    locale={lang}
                    resources={resources}>
                    {children}
                  </TranslationsProvider>
                </RedirectProvider>
                <NotificationGroup />
              </ErrorBoundary>
            </DialogContextProvider>
          </body>
        </StoreProvider>
      </GenAiClerkProvider>
    </html>
  );
}
