#!/bin/bash
#
################################################################################
# This script creates a FSx for ONTAP volume. It is depenent on
# a CloudFormation template that uses the NetApp CloudFormation
# custom resources. The template is passed as an argument to the script.
################################################################################

################################################################################
################################################################################
usage () {
cat <<EOF
Usage: $(basename $0) [-r region] -l link_ARN -s secret_ARN [-k secret_key] -f fsx_id -v svm_name -n volune_name [-z size_in_MB] [-a aggregate] -t template
Notes:
  The default region is the region configured in the AWS CLI.
  The default secret key is 'credentials'.
  The default aggregate is "aggr1".
  The default size is 20MB.
EOF
}
#
# Set the default values.
linkArn=""
secretArn=""
secretKey="credentials"
fsxId=""
volumeName=""
svmName=""
size="$((20*1024*1024))"
aggregates="aggr1"

region=$(aws configure list | awk '/region/{print $2}')

while getopts "hr:l:s:k:f:v:n:z:a:t:" opt; do
  case $opt in
    r) region=$OPTARG
      ;;
    l) linkArn=$OPTARG
      ;;
    s) secretArn=$OPTARG
      ;;
    k) secretKey=$OPTARG
      ;;
    f) fsxId=$OPTARG
      ;;
    v) svmName=$OPTARG
      ;;
    n) volumeName=$OPTARG
      ;;
    z) size=$((OPTARG*1024*1024))
      ;;
    a) aggregates=$OPTARG
      ;;
    t) template=$OPTARG
      ;;
    h)
      usage
      exit 1
      ;;
  esac
done

if [ -z "$region" -o -z "$linkArn" -o -z "$secretArn" -o -z "$fsxId" -o -z "$svmName" -o -z "$volumeName" -o -z "$template" ]; then
  echo "Missing required arguments."
  usage
  exit 1
fi

if [ ! -r "$template" ]; then
  echo "Cannot read template file '$template'."
  usage
  exit 1
fi
body=$(cat "$template")
#
# Since for some craze reason the aws command treats a strings with a comma
# as a list of strings, we have to escape the commas.
aggregates=$(echo $aggregates | sed -e 's/,/\\,/g')
stackName="create-volume-$$"
aws cloudformation create-stack --region $region --stack-name $stackName --template-body "$body" --parameters \
  ParameterKey=FileSystemId,ParameterValue=$fsxId \
  ParameterKey=SecretArn,ParameterValue=$secretArn \
  ParameterKey=SecretKey,ParameterValue=$secretKey \
  ParameterKey=LinkArn,ParameterValue=$linkArn \
  ParameterKey=VolumeName,ParameterValue=$volumeName \
  ParameterKey=SvmName,ParameterValue=$svmName \
  ParameterKey=Size,ParameterValue=$size \
  ParameterKey=Aggregates,ParameterValue=$aggregates 
