#!/bin/bash
#
################################################################################
# This script creates a snapshot of an FSx for ONTAP volume.
# It is dependent of a CloudFormation template that uses the
# Netapp CloudFormation custom resources. The template is passed as an argument.
################################################################################

################################################################################
################################################################################
usage () {
cat <<EOF
Usage: $(basename $0) [-r region] -l link_ARN -s secret_ARN [-k secret_key] -f fsx_id -v svm_name -n volume_name -p snapshot_name -t templete_filename
Notes:
  The default region is the region configured in the AWS CLI.
  The default secret key is 'credentials'.
EOF
}
#
# Set the default values.
linkArn=""
secretArn=""
secretKey="credentials"
fsxId=""
svmName=""
volumeName=""
snapshotName=""
template=""

region=$(aws configure list | awk '/region/{print $2}')

while getopts "hr:l:s:k:f:v:n:p:t:" opt; do
  case $opt in
    r) region=$OPTARG
      ;;
    l) linkArn=$OPTARG
      ;;
    s) secretArn=$OPTARG
      ;;
    k) secretKey=$OPTARG
      ;;
    f) fsxId=$OPTARG
      ;;
    v) svmName=$OPTARG
      ;;
    n) volumeName=$OPTARG
      ;;
    p) snapshotName=$OPTARG
      ;;
    t) template=$OPTARG
      ;;
    h) usage
      exit 1
      ;;
  esac
done

if [ -z "$region" -o -z "$linkArn" -o -z "$secretArn" -o -z "$fsxId" -o -z "$svmName" -o -z "$volumeName" -o -z "$snapshotName" -o -z "$template" ]; then
  echo "Missing required arguments."
  usage
  exit 1
fi

if [ ! -r "$template" ]; then
  echo "Cannot read template file '$template'."
  usage
  exit 1
fi
body=$(cat "$template")

stackName="create-snapshot-$$"
aws cloudformation create-stack --region $region --stack-name $stackName --template-body "$body" --parameters \
  ParameterKey=FileSystemId,ParameterValue=$fsxId \
  ParameterKey=SecretArn,ParameterValue=$secretArn \
  ParameterKey=SecretKey,ParameterValue=$secretKey \
  ParameterKey=LinkArn,ParameterValue=$linkArn \
  ParameterKey=VolumeName,ParameterValue=$volumeName \
  ParameterKey=SnapshotName,ParameterValue=$snapshotName \
  ParameterKey=SvmName,ParameterValue=$svmName 
