#!/bin/bash
#
################################################################################
# This script is used to create a SnapMirror relationship between two volumes 
# in two different SVMs in two different file systems. It is dependent on a
# a CloudFormation template that uses the NetApp CloudFormation extension. The
# template should be passed as a parameter to this script. The template
# assumes that the destination volume does not already exist.
################################################################################

################################################################################
################################################################################
usage () {
cat <<EOF
Usage: $(basename $0) [--region region] --source-link-arn link_arn --source-secret-arn secret_arn [--source-secret-key key] --source-fsx fsx_id --source-svm svm_name  --source-vol vol_name \\
                                          --dest-link-arn link_arn   --dest-secret-arn secret_arn   [--dest-sceret-key key]   --dest-fsx fsx_id   --dest-svm svm_name [--dest-vol vol_name_dp] \\
                               --template templete_filename [--dest-aggr aggregate1]
Notes:
  The default region is whatever the default region is in the AWS CLI configuration.
  The default secret key is 'credentials'.
  The default destination volume name is the source volume name with '_dp' appended.
  The default aggregate is 'aggr1'.
EOF
}
#
# Instead of passing a bunch of parameters, set the values of the variables here.
sourceLinkArn=""
sourceSecretArn=""
sourceSecretKey="credentials"
sourceFsxId=""
sourceSvmName=""
sourceVolumeName=""
destinationLinkArn=""
destinationSecretArn=""
destinationSecretKey="credentials"
destinationFsxId=""
destinationSvmName=""
destinationAggregate="aggr1"
template=""
#
# Get the default region from the AWS CLI configuration
region=$(aws configure list | awk '/region/{print $2}')
#
# Parse the command line arguments
while [ ! -z "$1" ]; do
  if [ "$1" == "--region" ]; then
    region=$2
    shift 1
  elif [ "$1" == "--source-link-arn" ]; then
    sourceLinkArn=$2
    shift 1
  elif [ "$1" == "--source-secret-arn" ]; then
    sourceSecretArn=$2
    shift 1
  elif [ "$1" == "--source-secret-key" ]; then
    sourceSecretKey=$2
    shift 1
  elif [ "$1" == "--source-fsx" ]; then
    sourceFsxId=$2
    shift 1
  elif [ "$1" == "--source-svm" ]; then
    sourceSvmName=$2
    shift 1
  elif [ "$1" == "--source-vol" ]; then
    sourceVolumeName=$2
    shift 1
  elif [ "$1" == "--dest-link-arn" ]; then
    destinationLinkArn=$2
    shift 1
  elif [ "$1" == "--dest-secret-arn" ]; then
    destinationSecretArn=$2
    shift 1
  elif [ "$1" == "--dest-secret-key" ]; then
    destinationSecretKey=$2
    shift 1
  elif [ "$1" == "--dest-fsx" ]; then
    destinationFsxId=$2
    shift 1
  elif [ "$1" == "--dest-svm" ]; then
    destinationSvmName=$2
    shift 1
  elif [ "$1" == "--dest-vol" ]; then
    destinationVolumeName=$2
    shift 1
  elif [ "$1" == "--dest-aggrs" ]; then
    destinationAggregate=$2
    shift 1
  elif [ "$1" == "--template" ]; then
    template=$2
    shift 1
  else
    echo "Unknown option '$1'."
    usage
    exit 1
  fi
  shift 1
done

if [ -z "$destinationVolumeName" ]; then
  destinationVolumeName="${sourceVolumeName}_dp"
fi

if [ -z "$sourceLinkArn" -o -z "$sourceSecretArn" -o -z "$sourceFsxId" -o -z "$sourceSvmName" -o -z "$sourceVolumeName" -o \
     -z "$destinationLinkArn" -o -z "$destinationSecretArn" -o -z "$destinationFsxId" -o -z "$destinationSvmName" ]; then
  echo "Missing required parameter."
  usage
  exit 1
fi

if [ ! -r "$template" ]; then
  echo "Cannot read template file '$template'."
  usage
  exit 1
fi
body=$(cat "$template")

stackName="create-snapmirror-relationship-$$"
aws cloudformation create-stack --region $region --stack-name $stackName --template-body "$body" --parameters \
  ParameterKey=SourceLinkArn,ParameterValue=$sourceLinkArn \
  ParameterKey=SourceSecretArn,ParameterValue=$sourceSecretArn \
  ParameterKey=SourceSecretKey,ParameterValue=$sourceSecretKey \
  ParameterKey=SourceFileSystemId,ParameterValue=$sourceFsxId \
  ParameterKey=SourceSvmName,ParameterValue=$sourceSvmName \
  ParameterKey=SourceVolumeName,ParameterValue=$sourceVolumeName \
  ParameterKey=DestinationLinkArn,ParameterValue=$destinationLinkArn \
  ParameterKey=DestinationSecretArn,ParameterValue=$destinationSecretArn \
  ParameterKey=DestinationSecretKey,ParameterValue=$destinationSecretKey \
  ParameterKey=DestinationFileSystemId,ParameterValue=$destinationFsxId \
  ParameterKey=DestinationSvmName,ParameterValue=$destinationSvmName \
  ParameterKey=DestinationVolumeName,ParameterValue=$destinationVolumeName \
  ParameterKey=DestinationAggregate,ParameterValue=$destinationAggregate
