#!/bin/bash

sed -e '/ZipFile/,$d' cloudformation.yaml > cloudformation.yaml.tmp
echo "        ZipFile: |" >> cloudformation.yaml.tmp
cat monitor_ontap_services.py | sed 's/^/          /' >> cloudformation.yaml.tmp
if diff cloudformation.yaml cloudformation.yaml.tmp; then
    rm -f cloudformation.yaml.tmp 
    echo "No changes detected"
    exit 0
fi
echo "Updating cloudformation.yaml"
mv cloudformation.yaml.tmp cloudformation.yaml
