---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logs-config
  labels:
    app: '{{ template "filebeat.fullname" . }}-logs-config'
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        paths:
          - /logs/*/*.log
    output.console:
      pretty: true


