apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment
  namespace: rpc
  labels:
    app: eks-sample-linux-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: rpc-app-pvc
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.23
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        volumeMounts:
          - mountPath: "/log"
            subPathExpr: $(NODE_NAME)/$(POD_NAME)
            name: task-pv-storage
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux