# Title: delete_cifs_share.yaml

---
- name: Playbook to delete a CIFS share
  hosts: localhost
  collections:
    - netapp.ontap
    - amazon.aws
  gather_facts: false
  vars_files:
    - variables.yaml
  vars:
    use_lambda: false

  tasks:
    - name: Ensure required variables are set.
      fail:
        msg: "Required variable {{item}} has not been provided."
      when: vars[item] is undefined
      loop:
        - delete_share_name
        - vserver
        - secret_name
        - fsxn_hostname

    - name: Set use_lambda to true if lambda_function_name is provided.
      set_fact:
        use_lambda: true
      when: lambda_function_name is defined
    
    - name: Ensure that aws_region has been provided if use_lambda is true.
      fail:
        msg: "aws_region must be defined when use_lambda is true."
      when: use_lambda and aws_region is not defined
    
    - name: Get username and password from AWS secret.
      set_fact:
        username: "{{ lookup('amazon.aws.aws_secret', '{{ secret_name }}.username', nested=true) }}"
        password: "{{ lookup('amazon.aws.aws_secret', '{{ secret_name }}.password', nested=true) }}"
      no_log: true

    - name: Delete CIFS Share
      netapp.ontap.na_ontap_cifs:
        state: absent
        hostname: "{{ fsxn_hostname }}"
        vserver: "{{ vserver }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        use_lambda: "{{ use_lambda }}"
        lambda_config:
          aws_profile: "{{ aws_profile | default('default') }}"
          aws_region: "{{ aws_region | default('') }}"
          function_name: "{{ lambda_function_name | default('') }}"

        name: "{{ delete_share_name }}"
