volume_name: "test_volume"
volume_size: 1024
vserver: "fsx"
fsxn_hostname: "10.1.1.1"
lambda_function_name: "lambda-aaaaaaaa"
aws_region: "us-west-2"
secret_name: "fsxn/default"
snapshot_name: "test_snapshot"
autosize_mode: "grow"
