volume_name: "keith_test_ansible"
volume_size: 1024
vserver: "smb_svm"
fsxn_hostname: "10.100.13.122"
lambda_function_name: "demo-vpc-wf-link"
aws_region: "us-west-2"
secret_name: "keith/fsxn/default"
snapshot_name: "test_snapshot_from_ansible"
autosize_mode: "grow"
