#!/bin/bash
################################################################################
#
# This script is used to set the fsxadmin password for a FSxN file system.
################################################################################

################################################################################
#  This function just outputs the usage information and exits.
################################################################################
usage () {
cat 1>&2 <<EOF
Usage: $(basename $0) [-p password] [-f fileSystemName] [-i fileSystemId] [-r region] [-w] [-e endpoint_url]
Where:
  password: Is the password to set for the fsxadmin user. If not provided, the script will prompt for it.
  fileSystemName: Is the name of the FSxN file system where you want set the password. This option is mutually exclusive with the -i option.
  fileSystemID: Is the file system ID where you want to set the password. This option is mutually exclusive with the -f option.
  region: Is the AWS region where the FSxN file system resides.
  -w : Wait for the password to be set before returning.
  endpoint_url: Is the endpoint url to use when connecting to the AWS API.

NOTE: You must provide either the file system name or the file system ID. You cannot provide both.
EOF
  exit 1
}

################################################################################
# Main logic starts here.
################################################################################
tmpout=/tmp/create_svm.$$
trap 'rm -f $tmpout' exit

if which aws jq > /dev/null 2>&1; then
  :
else
  echo "Error, both the 'aws' and 'jq' commands are required to run this script." 1>&2
  exit 1
fi
#
# Set some defaults.
region=$(aws configure get region)
waitForCompletion=false
maxIterations=24
sleepTime=5
#
# Process command line arguments.
while getopts "hwp:r:f:i:e:" option; do
  case $option in
    p) password=$OPTARG
      ;;
    r) region=$OPTARG
      ;;
    f) fileSystemName=$OPTARG
      ;;
    i) fsid=$OPTARG
      ;;
    w) waitForCompletion=true
      ;;
    e) endpoint_url="--endpoint-url $OPTARG"
      ;;
    *) usage
      ;;
  esac
done

if [ ! -z "$fileSystemName" -a ! -z "$fsid" ]; then
  echo "Error, you can only specify the -i OR the -f option. Not both." 1>&2
  usage
fi
#
# Ensure all the required parameters have been provided.
if [ -z "$fileSystemName" -a -z "$fsid" ]; then
  echo "Error, missing required arguments." 1>&2
  usage
fi

if [ -z "$password" ]; then
  read -sp "Enter the password to set for the fsxadmin user: " password1
  echo ""
  read -sp "Confirm the password: " password2
  echo ""
  if [ "$password1" != "$password2" ]; then
    echo "Error, the passwords do not match." 1>&2
    exit 1
  else
    password=$password1
  fi
fi
#
# Ensure all the required parameters have been provided.
if [ -z "$password" ]; then
  echo "Error, the password can't be blank."
  usage
fi
#
# Get the file system id from the file system name.
if [ -z "$fsid" ]; then
  fsid=$(aws fsx describe-file-systems $endpoint_url --region $region --output=json 2> /dev/null | jq -r ".FileSystems[] | if((.Tags[] | select(.Key == \"Name\") .Value) == \"${fileSystemName}\") then .FileSystemId else empty end" 2> /dev/null)
fi

if [ -z "$fsid" ]; then
  echo "Error, could not find the file system with name '${fileSystemName}' in region $region." 1>&2
  exit 1
fi
#
# Set the password
aws fsx update-file-system $endpoint_url --ontap-configuration '{"FsxAdminPassword": "'"$password"'"}'  --region=$region --file-system-id "$fsid" --output=json > $tmpout 2>&1
if [ $? != "0" ]; then
  echo "Failed to set the password." 1>&2
  cat $tmpout 1>&2
  exit 1
else
  status=$(jq -r .FileSystem.AdministrativeActions[0].Status $tmpout 2> /dev/null)
  if [ "$status" == "PENDING" ]; then
    printf "Password is being set."
    #
    # Wait for the svm to be deleted.
    if [ $waitForCompletion == true ]; then
      i=0
      while [ $i -lt $maxIterations ]; do
        aws fsx describe-file-systems $endpoint_url --file-system-id $fsid --output=json --region=$region > $tmpout 2>&1
        if [ $? -eq 0 ]; then
          #
          # Assume the first administrative action is the one we just created.
          status=$(jq -r .FileSystems[0].AdministrativeActions[0].Status $tmpout 2> /dev/null)
          if [ "$status" == "COMPLETED" ]; then
            printf "\nPassword has been set.\n"
            break
          fi
          if [ "$status" != "PENDING" -a "$status" != "IN_PROGRESS" ]; then
            printf "\nError, failed to set the password on '$fsid'. Status = $status\n" 1>&2
            if [ "$status" == "FAILED" ]; then
              jq -r .FileSystems[0].AdministrativeActions[0].FailureDetails.Message $tmpout 1>&2
            fi
            exit 1
          fi
        else
          printf "\nError, failed to get status of filesystem with ID '$fsid'.\n" 1>&2
          cat $tmpout 1>&2
          exit 1
        fi
        printf "."
        sleep $sleepTime
        let i+=1
      done
      if [ $i -ge $maxIterations ]; then
        printf "\nFailed to set the password on file system id '$fsid'. Taking too long.\n" 1>&2
        exit 1
      fi
    else
      printf "\n"
    fi
  else
    echo "Unknown status '$status'. Complete output returned from the AWS api:" 1>&2
    cat $tmpout 1>&2
    exit 1
  fi
fi
exit 0
