---
# Copyright (c) NetApp, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Super-linter
        uses: super-linter/super-linter@v5.7.2  # x-release-please-version
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks, you must provide a GitHub token.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          BASH_SEVERITY: "error"
          VALIDATE_GITHUB_ACTIONS: true
          # VALIDATE_MARKDOWN: true
          # VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_POWERSHELL: true
          # VALIDATE_TERRAFORM_FMT: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML: true  
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_TYPESCRIPT_ES: true
