# Copyright (c) NetApp, Inc.
# SPDX-License-Identifier: Apache-2.0

name: "Documentation: terraform-docs"

on:
  pull_request:
    paths:
      - "Terraform/**"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request  
        uses: actions/checkout@v3.5.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render documentation and push changes back to branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: Terraform/*
          config-file: ".terraform-docs.yml"
          output-file: "README.md"
          output-method: replace
          git-push: true
