---
# Copyright (c) NetApp, Inc.
# SPDX-License-Identifier: Apache-2.0

name: "Code Quality: Terraform"

on:
  pull_request:
    paths:
      - 'Terraform/**'
  push:
    paths:
      - 'Terraform/**'
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - 'Terraform/deploy-fsx-ontap/module'
          - 'Terraform/deploy-fsx-ontap/standalone-module'
    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - name: Checkout pull request
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.6.6

      - name: Initialize Terraform
        run: terraform init

      # - name: Format Terraform configuration
      #   run: terraform fmt -diff -check -no-color -recursive

      - name: Validate Terraform configuration
        run: terraform validate