---
# Copyright (c) NetApp, Inc.
# SPDX-License-Identifier: Apache-2.0

name: "Code Quality: Terraform"

on:
  pull_request:
    paths:
      - 'Infrastructure_as_Code/Terraform/**'
  push:
    paths:
      - 'Infrastructure_as_Code/Terraform/**'
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - 'Infrastructure_as_Code/Terraform/deploy-fsx-ontap/module'
          - 'Infrastructure_as_Code/Terraform/deploy-fsx-ontap/standalone-module'
    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout pull request
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@ed3a0531877aca392eb870f440d9ae7aba83a6bd # v1.4.0
        with:
          terraform_wrapper: false
          terraform_version: 1.6.6

      - name: Initialize Terraform
        run: terraform init

      # - name: Format Terraform configuration
      #   run: terraform fmt -diff -check -no-color -recursive

      - name: Validate Terraform configuration
        run: terraform validate
